table dim_Customer
    lineageTag: dim-Customer-001

    column CustomerKey
        dataType: int64
        lineageTag: dim-Customer-ck
        summarizeBy: none
        isHidden: true

    column CustID
        dataType: int64
        lineageTag: dim-Customer-srcid
        summarizeBy: none
        isHidden: true

    column CustomerName
        dataType: string
        lineageTag: dim-Customer-name
        summarizeBy: none

    column CustomerEmail
        dataType: string
        lineageTag: dim-Customer-email
        summarizeBy: none

    column CustomerSegment
        dataType: string
        lineageTag: dim-Customer-seg
        summarizeBy: none

    partition dim_Customer = m
        mode: import
        source =
                let
                    Source = Excel.Workbook(File.Contents("C:\\Users\\FrederickAmougou\\Projects\\powerbi-mcp-demo-model-refactor\\messy_sales_raw.xlsx"), null, true),
                    Sheet1 = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
                    Promoted = Table.PromoteHeaders(Sheet1, [PromoteAllScalars=true]),
                    Changed = Table.TransformColumnTypes(Promoted,{{"Cust ID", Int64.Type}, {"Customer Name", type text}, {"customer_email", type text}, {"Customer Segment", type text}}),
                    Distinct = Table.Distinct(Table.SelectColumns(Changed,{"Cust ID","Customer Name","customer_email","Customer Segment"})),
                    WithIndex = Table.AddIndexColumn(Distinct, "CustomerKey", 1, 1, Int64.Type),
                    Renamed = Table.RenameColumns(WithIndex,{{"Cust ID","CustID"},{"customer_email","CustomerEmail"},{"Customer Name","CustomerName"},{"Customer Segment","CustomerSegment"}})
                in
                    Renamed

    annotation PBI_ResultType = Table
