table fact_Sales
    lineageTag: fact-Sales-refactored-001

    column OrderID
        dataType: string
        lineageTag: fs-OrderID
        summarizeBy: none

    column CustomerKey
        dataType: int64
        lineageTag: fs-CustomerKey
        summarizeBy: none
        isHidden: true

    column ProductKey
        dataType: string
        lineageTag: fs-ProductKey
        summarizeBy: none
        isHidden: true

    column DateKey
        dataType: int64
        lineageTag: fs-DateKey
        summarizeBy: none
        isHidden: true

    column SalespersonKey
        dataType: string
        lineageTag: fs-SalespersonKey
        summarizeBy: none
        isHidden: true

    column Qty
        dataType: int64
        lineageTag: fs-Qty
        summarizeBy: sum

    column UnitPrice
        dataType: double
        lineageTag: fs-UnitPrice
        summarizeBy: sum

    column DiscountPct
        dataType: double
        lineageTag: fs-DiscountPct
        summarizeBy: sum

    column Gross_Amount
        dataType: double
        lineageTag: fs-Gross
        summarizeBy: sum

    column NetAmount
        dataType: double
        lineageTag: fs-Net
        summarizeBy: sum

    column Tax Amount
        dataType: double
        lineageTag: fs-Tax
        summarizeBy: sum

    column Total Amount
        dataType: double
        lineageTag: fs-Total
        summarizeBy: sum

    column Order_Status
        dataType: string
        lineageTag: fs-OrderStatus
        summarizeBy: none

    column is_renewal
        dataType: bool
        lineageTag: fs-isrenewal
        summarizeBy: none

    partition fact_Sales = m
        mode: import
        source =
                let
                    Source = Excel.Workbook(File.Contents("C:\\Users\\FrederickAmougou\\Projects\\powerbi-mcp-demo-model-refactor\\messy_sales_raw.xlsx"), null, true),
                    Sheet1 = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
                    Promoted = Table.PromoteHeaders(Sheet1, [PromoteAllScalars=true]),
                    // Parse candidate date fields and choose canonical OrderDate
                    Parsed = Table.TransformColumnTypes(Promoted,{{"order_dt", type date}, {"Date_of_Order", type datetime}, {"orderdate", type text}, {"Order Date", type text}, {"Cust ID", Int64.Type}, {"Qty", type any}, {"Unit Price", type any}, {"discount %", Int64.Type}, {"Gross_Amount", type number}, {"NetAmount", type number}, {"Tax Amount", type number}, {"Total Amount", type number}, {"is_renewal", type text}}),
                    AddOrderDate = Table.AddColumn(Parsed, "OrderDate", each if Record.FieldOrDefault(_, "order_dt") <> null then Date.From(Record.Field(_, "order_dt")) else if Record.FieldOrDefault(_, "Date_of_Order") <> null then Date.From(Record.Field(_, "Date_of_Order")) else try Date.From(DateTime.FromText(Record.Field(_, "orderdate"))) otherwise try Date.From(DateTime.FromText(Record.Field(_, "Order Date"))) otherwise null, type date),
                    AddDateKey = Table.AddColumn(AddOrderDate, "DateKey", each if [OrderDate] <> null then Number.From(Date.Year([OrderDate]))*10000 + Number.From(Date.Month([OrderDate]))*100 + Number.From(Date.Day([OrderDate])) else null, Int64.Type),
                    // Convert numeric-ish fields
                    ToQty = Table.AddColumn(AddDateKey, "Qty_num", each try Number.From(Text.Trim(Text.From([Qty]))) otherwise null, Int64.Type),
                    ToUnitPrice = Table.AddColumn(ToQty, "UnitPrice_num", each try Number.From(Text.Remove(Text.From([Unit Price]),{"$","£",","})) otherwise null, type number),
                    ToDiscount = Table.AddColumn(ToUnitPrice, "DiscountPct", each try if [discount %] <> null then Number.From([discount %]) / 100.0 else try Number.From(Text.Replace(Text.From([discount %]),"%",""))/100.0 otherwise null, type number),
                    ToIsRenew = Table.AddColumn(ToDiscount, "is_renewal_bool", each let v = Text.Lower(Text.Trim(Text.From(Record.FieldOrDefault(_, "is_renewal")))) in if v = "yes" or v = "true" or v = "y" or v = "1" then true else if v = "no" or v = "false" or v = "n" or v = "0" then false else null, type logical),
                    // Build final fact projection using original keys for joins
                    Final = Table.SelectColumns(ToIsRenew,{"OrderID","Cust ID","Product ID","DateKey","Salesperson","Qty_num","UnitPrice_num","DiscountPct","Gross_Amount","NetAmount","Tax Amount","Total Amount","Order_Status","is_renewal_bool"}),
                    Renamed = Table.RenameColumns(Final,{{"Cust ID","CustomerKey"},{"Product ID","ProductKey"},{"Salesperson","SalespersonKey"},{"Qty_num","Qty"},{"UnitPrice_num","UnitPrice"},{"is_renewal_bool","is_renewal"}})
                in
                    Renamed

    annotation PBI_ResultType = Table
