table SalesRaw
	lineageTag: d131fb43-3cc0-47db-8163-8235a01f2c46

	column OrderID
		dataType: string
		lineageTag: d8dbc2a8-b009-4d06-b40e-9294d47fdf79
		summarizeBy: none
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: string
		lineageTag: b32e88c2-262a-4e61-acd4-c862ff9d76ae
		summarizeBy: none
		sourceColumn: Order Date

		annotation SummarizationSetBy = Automatic

	column orderdate
		dataType: string
		lineageTag: bec69fce-293a-488b-a3b3-ce6f37192800
		summarizeBy: none
		sourceColumn: orderdate

		annotation SummarizationSetBy = Automatic

	column Date_of_Order
		dataType: dateTime
		formatString: General Date
		lineageTag: b1724322-c6a1-4727-969d-70fdabf6d695
		summarizeBy: none
		sourceColumn: Date_of_Order

		annotation SummarizationSetBy = Automatic

	column 'Cust ID'
		dataType: int64
		formatString: 0
		lineageTag: 70202567-bb79-40a7-af16-bbe76d4a2779
		summarizeBy: count
		sourceColumn: Cust ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: ae5d439b-4170-4b96-9f51-518a17e0b741
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column customer_email
		dataType: string
		lineageTag: 420538a8-67b2-48dd-acd3-52de3b1471bb
		summarizeBy: none
		sourceColumn: customer_email

		annotation SummarizationSetBy = Automatic

	column 'Customer Segment'
		dataType: string
		lineageTag: 4f984d1b-cfff-4de9-9ad6-3176455e555d
		summarizeBy: none
		sourceColumn: Customer Segment

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: ae8bfd0d-caf2-4941-bc9b-e90386fa6e7e
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Salesperson
		dataType: string
		lineageTag: 710a4f9a-31f0-465e-abbb-60c1dceb1b48
		summarizeBy: none
		sourceColumn: Salesperson

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: 205f68c6-d896-4e3f-a759-b33132a534db
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 25bca956-5ca9-4740-ae15-2a69e09f01f5
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: df3b46cf-7bb7-4c88-a622-1f4e25ce5808
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column product_category
		dataType: string
		lineageTag: faf4bcdd-cdd5-4560-bb6e-834c2a76ef7a
		summarizeBy: none
		sourceColumn: product_category

		annotation SummarizationSetBy = Automatic

	column Qty
		dataType: string
		lineageTag: a8c538ca-6ec9-4fa0-8b72-ade61c5e4087
		summarizeBy: none
		sourceColumn: Qty

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: string
		lineageTag: 885dfe32-9b88-45a0-bc90-2e4719271125
		summarizeBy: none
		sourceColumn: Unit Price

		annotation SummarizationSetBy = Automatic

	column 'discount %'
		dataType: int64
		formatString: 0
		lineageTag: a3c51b54-ac32-4d5a-95de-ae1e2f6ce5bc
		summarizeBy: sum
		sourceColumn: discount %

		annotation SummarizationSetBy = Automatic

	column Gross_Amount
		dataType: double
		lineageTag: 32d1c947-0a82-4bb4-aefd-f809b37103e0
		summarizeBy: sum
		sourceColumn: Gross_Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NetAmount
		dataType: double
		lineageTag: d07728d8-e8fc-4dc2-b205-9b12324b7373
		summarizeBy: sum
		sourceColumn: NetAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Tax Amount'
		dataType: double
		lineageTag: 1daae04d-9cf7-43bd-b9dd-89ab71ffc0b7
		summarizeBy: sum
		sourceColumn: Tax Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Amount'
		dataType: double
		lineageTag: b5ede44d-d7e5-4eb2-bfb8-4aab50dd6049
		summarizeBy: sum
		sourceColumn: Total Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Order_Status
		dataType: string
		lineageTag: 4b918aee-d8da-4fe3-943d-042e0460915c
		summarizeBy: none
		sourceColumn: Order_Status

		annotation SummarizationSetBy = Automatic

	column order_dt
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5a9fb305-5db4-45db-a908-305f1a2c42a9
		summarizeBy: none
		sourceColumn: order_dt

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column order_month_txt
		dataType: dateTime
		formatString: Long Date
		lineageTag: 72411800-7c70-4565-a305-8604b2b2dd9f
		summarizeBy: none
		sourceColumn: order_month_txt

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Year'
		dataType: int64
		formatString: 0
		lineageTag: 511f27e4-a2e3-4b04-8dc8-4cc5112db921
		summarizeBy: sum
		sourceColumn: Fiscal Year

		annotation SummarizationSetBy = Automatic

	column is_renewal
		dataType: string
		lineageTag: d8960b53-aae3-425f-a49b-da5fcf9b6d62
		summarizeBy: none
		sourceColumn: is_renewal

		annotation SummarizationSetBy = Automatic

	partition SalesRaw = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\FrederickAmougou\Projects\powerbi-mcp-demo-model-refactor\messy_sales_raw.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"OrderID", type text}, {"Order Date", type text}, {"orderdate", type any}, {"Date_of_Order", type datetime}, {"Cust ID", Int64.Type}, {"Customer Name", type text}, {"customer_email", type text}, {"Customer Segment", type text}, {"Region", type text}, {"Salesperson", type text}, {"channel", type text}, {"Product ID", type text}, {"Product Name", type text}, {"product_category", type text}, {"Qty", type any}, {"Unit Price", type any}, {"discount %", Int64.Type}, {"Gross_Amount", type number}, {"NetAmount", type number}, {"Tax Amount", type number}, {"Total Amount", type number}, {"Order_Status", type text}, {"order_dt", type date}, {"order_month_txt", type date}, {"Fiscal Year", Int64.Type}, {"is_renewal", type any}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

