table SalesRaw
	lineageTag: f807f169-1d76-4b23-af47-95159b4915a7

	column OrderID
		dataType: string
		lineageTag: cc7c28e1-4e0e-432b-aa42-1f89d68380e6
		summarizeBy: none
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: string
		lineageTag: a72a1a16-622e-4371-b129-237195cf4d41
		summarizeBy: none
		sourceColumn: Order Date

		annotation SummarizationSetBy = Automatic

	column orderdate
		dataType: string
		lineageTag: 3a34fa88-fe9b-4e92-a513-aedbd654dcb6
		summarizeBy: none
		sourceColumn: orderdate

		annotation SummarizationSetBy = Automatic

	column Date_of_Order
		dataType: dateTime
		formatString: General Date
		lineageTag: 455e908a-a49a-44d4-96e5-842b286ba31a
		summarizeBy: none
		sourceColumn: Date_of_Order

		annotation SummarizationSetBy = Automatic

	column 'Cust ID'
		dataType: int64
		formatString: 0
		lineageTag: dada90b0-029b-4326-bdd4-0585a84a1714
		summarizeBy: count
		sourceColumn: Cust ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 5d289bcf-987e-4dca-81ea-9401846ce254
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column customer_email
		dataType: string
		lineageTag: 77fd2fbb-ad54-47e1-9ab9-cee59d30adee
		summarizeBy: none
		sourceColumn: customer_email

		annotation SummarizationSetBy = Automatic

	column 'Customer Segment'
		dataType: string
		lineageTag: 628c3e26-7f28-49eb-b219-4cc12877a4f0
		summarizeBy: none
		sourceColumn: Customer Segment

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 4caef962-3ec1-426a-9206-f28268b362a3
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Salesperson
		dataType: string
		lineageTag: 01c61eae-3e30-4658-84d9-6551059a0892
		summarizeBy: none
		sourceColumn: Salesperson

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: d8eb0f9a-2e31-432f-b758-a147f25ccf77
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 615277cf-3b5a-418a-8dbe-afe70fa1e68a
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 73eafd38-a889-4e9d-88fe-6afcc307b43a
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column product_category
		dataType: string
		lineageTag: d0e78839-4c9c-4034-bbe8-65c39eef19ad
		summarizeBy: none
		sourceColumn: product_category

		annotation SummarizationSetBy = Automatic

	column Qty
		dataType: string
		lineageTag: 27097909-12f5-46dc-b2ed-04aaf57380e7
		summarizeBy: none
		sourceColumn: Qty

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: string
		lineageTag: dfbb77e6-e6b0-44d4-bf88-46c5a3e24a19
		summarizeBy: none
		sourceColumn: Unit Price

		annotation SummarizationSetBy = Automatic

	column 'discount %'
		dataType: int64
		formatString: 0
		lineageTag: 818c71fc-c501-4ddc-a19b-bc90eaf2b6d1
		summarizeBy: sum
		sourceColumn: discount %

		annotation SummarizationSetBy = Automatic

	column Gross_Amount
		dataType: double
		lineageTag: 2ba4f6c9-3a32-405f-9b90-280eb80c59eb
		summarizeBy: sum
		sourceColumn: Gross_Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NetAmount
		dataType: double
		lineageTag: f71a474a-1964-47b9-8e8e-38edd062ce9b
		summarizeBy: sum
		sourceColumn: NetAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Tax Amount'
		dataType: double
		lineageTag: c837ff25-76a1-44a9-ac1f-e89b70160f0f
		summarizeBy: sum
		sourceColumn: Tax Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Amount'
		dataType: double
		lineageTag: 8d70060b-307a-4132-abec-0925ff5473ac
		summarizeBy: sum
		sourceColumn: Total Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Order_Status
		dataType: string
		lineageTag: 21101f2b-cf27-404f-99f2-e6689740690d
		summarizeBy: none
		sourceColumn: Order_Status

		annotation SummarizationSetBy = Automatic

	column order_dt
		dataType: dateTime
		formatString: Long Date
		lineageTag: 67352310-c467-46da-9fca-bb0d9af48626
		summarizeBy: none
		sourceColumn: order_dt

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column order_month_txt
		dataType: dateTime
		formatString: Long Date
		lineageTag: e82f812a-be8f-40ba-8846-e3e4ea12a4f5
		summarizeBy: none
		sourceColumn: order_month_txt

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Year'
		dataType: int64
		formatString: 0
		lineageTag: 54d48794-22a4-402f-90aa-8d0aaa8ed919
		summarizeBy: sum
		sourceColumn: Fiscal Year

		annotation SummarizationSetBy = Automatic

	column is_renewal
		dataType: string
		lineageTag: 77f43973-f6da-49d7-94b6-97af6966daab
		summarizeBy: none
		sourceColumn: is_renewal

		annotation SummarizationSetBy = Automatic

	partition SalesRaw = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\FrederickAmougou\Projects\powerbi-mcp-demo-model-refactor\messy_sales_raw.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"OrderID", type text}, {"Order Date", type text}, {"orderdate", type any}, {"Date_of_Order", type datetime}, {"Cust ID", Int64.Type}, {"Customer Name", type text}, {"customer_email", type text}, {"Customer Segment", type text}, {"Region", type text}, {"Salesperson", type text}, {"channel", type text}, {"Product ID", type text}, {"Product Name", type text}, {"product_category", type text}, {"Qty", type any}, {"Unit Price", type any}, {"discount %", Int64.Type}, {"Gross_Amount", type number}, {"NetAmount", type number}, {"Tax Amount", type number}, {"Total Amount", type number}, {"Order_Status", type text}, {"order_dt", type date}, {"order_month_txt", type date}, {"Fiscal Year", Int64.Type}, {"is_renewal", type any}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

